<?php

$VIDEO_CATEGORIES = [
  ['slug' => 'all',       'name' => 'All'],
  ['slug' => 'anatomy',     'name' => 'Anatomy'],
  ['slug' => 'latch',  'name' => 'Latch'],
  ['slug' => 'problems',  'name' => 'Problems'],
  ['slug' => 'position', 'name' => 'Proper position'],
  ['slug' => 'nutrition',   'name' => 'Nutrition'],
  ['slug' => 'techniques','name' => 'Techniques'],
];


$VIDEOS = [
    // Latch
  [
    'id' => 1,
    'title' => 'How to latch',
    'author' => 'wikiHow',
    'description' => 'A guide for proper latching and effective breastfeeding technique and making sure the infants are getting fed properly.',
    'category' => 'latch',
    'duration' => '4:01',
    'thumb' => 'public/images/thumbnails/latch/latch1.jpg',
    'src' => 'public/videos/latch/latch1.mp4',
  ],
  [
    'id' => 2,
    'title' => 'Latch on ',
    'author' => 'PigeonCorporation',
    'description' => 'A proper latch allows your baby to draw milk efficiently. It promotes steady milk flow, supports healthy weight gain, and encourages a strong milk supply making feeding smoother, more comfortable, and more rewarding for both mother and baby.',
    'category' => 'latch',
    'duration' => '2:28',
    'thumb' => 'public/images/thumbnails/latch/latch2.jpg',
    'src' => 'public/videos/latch/latch2.mp4',
  ],
//   Nutrition
  [
    'id' => 3,
    'title' => '15 Foods na Pamparami ng Breastmilk',
    'author' => 'Healing Galing',
    'description' => 'A practical guide on nutrient tips and diet strategies to support breastfeeding moms’ health, including foods to include for energy, hydration, and milk production',
    'category' => 'nutrition',
    'duration' => '14:12',
    'thumb' => 'public/images/thumbnails/nutrition/nutrition1.jpg',
    'src' => 'public/videos/nutrition/nutrition1.mp4',
  ],
  [
    'id' => 4,
    'title' => '10 Food to avoid During Pregnancy',
    'author' => 'FirstCry Parenting',
    'description' => 'Key guidance on what foods may affect your baby or breast milk negatively so you can adjust your diet with confidence while nursing.',
    'category' => 'nutrition',
    'duration' => '4:06',
    'thumb' => 'public/images/thumbnails/nutrition/nutrition2.jpg',
    'src' => 'public/videos/nutrition/nutrition2.mp4',
  ],
  [
    'id' => 5,
    'title' => '10 Best Foods to Increase Breast Milk',
    'author' => 'FirstCry Parenting',
    'description' => 'Discover the top 10 nutritious foods that can help breastfeeding moms boost milk production and stay energized with healthy, family-friendly nutrition tips.',
    'category' => 'nutrition',
    'duration' => '1:56',
    'thumb' => 'public/images/thumbnails/nutrition/nutrition3.jpg',
    'src' => 'public/videos/nutrition/nutrition3.mp4',
  ],
  [
    'id' => 6,
    'title' => '6 Best Fruits Every Breastfeeding Mom Should eat',
    'author' => 'FirstCry Parenting',
    'description' => 'Learn which 6 fruits are most beneficial to include in your breastfeeding diet for extra vitamins, hydration, and overall nourishment.',
    'category' => 'nutrition',
    'duration' => '3:51',
    'thumb' => 'public/images/thumbnails/nutrition/nutrition4.jpg',
    'src' => 'public/videos/nutrition/nutrition4.mp4',
  ],
//   Anatomy
  [
    'id' => 7,
    'title' => 'Female Breast Structure',
    'author' => 'Kenhub - Learn Human Anatomy',
    'description' => 'Discover the fascinating design and function of the female breast and how it produces and delivers life-nourishing milk.',
    'category' => 'anatomy',
    'duration' => '3:34',
    'thumb' => 'public/images/thumbnails/anatomy/anatomy1.jpg',
    'src' => 'public/videos/anatomy/anatomy1.mp4',
  ],
  [
    'id' => 8,
    'title' => 'How Breastfeeding happens?',
    'author' => 'Now Trending',
    'description' => 'From hormonally guided production to its nutrient-packed flow, breast milk is naturally crafted to feed, defend, and build your baby’s strength from the very first drop.',
    'category' => 'anatomy',
    'duration' => '3:41',
    'thumb' => 'public/images/thumbnails/anatomy/anatomy2.jpg',
    'src' => 'public/videos/anatomy/anatomy2.mp4',
  ],
//   Problems
  [
    'id' => 9,
    'title' => 'Poor Latch',
    'author' => 'Scottish Government',
    'description' => 'Latch right, feed bright. Secured attachment turns every feed into an effortless, nurturing experience',
    'category' => 'problems',
    'duration' => '1:04',
    'thumb' => 'public/images/thumbnails/problems/problems1.jpg',
    'src' => 'public/videos/problems/problems1.mp4',
  ],
  [
    'id' => 10,
    'title' => 'Mastitis',
    'author' => 'Dr. Constantin',
    'description' => 'Awareness today prevents complications tomorrow. Protected breast health, protects your milk flow.',
    'category' => 'problems',
    'duration' => '2:48',
    'thumb' => 'public/images/thumbnails/problems/problems2.jpg',
    'src' => 'public/videos/problems/problems2.mp4',
  ],
  [
    'id' => 11,
    'title' => 'Low Breast Milk Supply',
    'author' => 'FirstCry Parenting',
    'description' => 'When supply feels low, knowledge and support help it grow because understanding the causes, signs, and solutions can turn worry into action.',
    'category' => 'problems',
    'duration' => '4:08',
    'thumb' => 'public/images/thumbnails/problems/problems3.jpg',
    'src' => 'public/videos/problems/problems3.mp4',
  ],
  [
    'id' => 12,
    'title' => 'Breast Engorgement ',
    'author' => 'EvergreenHealth',
    'description' => 'Relieve engorgement, restore comfort. Keep your milk supply steady and feed your baby happy and healthy. ',
    'category' => 'problems',
    'duration' => '4:26',
    'thumb' => 'public/images/thumbnails/problems/problems4.jpg',
    'src' => 'public/videos/problems/problems4.mp4',
  ],
  [
    'id' => 13,
    'title' => 'Sore or Cracked Nipples ',
    'author' => 'Discover Parenting',
    'description' => 'Exploring the sore or cracked nipples, identifying their causes, and learning effective ways to prevent and treat them.',
    'category' => 'problems',
    'duration' => '2:44',
    'thumb' => 'public/images/thumbnails/problems/problems5.jpg',
    'src' => '/public/videos/problems/problems5.mp4',
  ],
//   Proper Position
  [
    'id' => 14,
    'title' => 'Cross - cradle position ',
    'author' => 'Emma’s Diary',
    'description' => 'Guide the head, support the body, cross-cradle makes feeding easy.',
    'category' => 'position',
    'duration' => '0:45',
    'thumb' => 'public/images/thumbnails/proper_position/proper_position1.jpg',
    'src' => 'public/videos/proper_position/proper_position1.mp4',
  ],
  [
    'id' => 15,
    'title' => 'Cradle Position',
    'author' => 'Emma’s Diary',
    'description' => 'Cradle the bond, cradle the baby. With this guide master the cradle hold with confidence and comfort.',
    'category' => 'position',
    'duration' => '0:44',
    'thumb' => 'public/images/thumbnails/proper_position/proper_position2.jpg',
    'src' => 'public/videos/proper_position/proper_position2.mp4',
  ],
  [
    'id' => 16,
    'title' => 'Back - Lying Position',
    'author' => 'Emma’s Diary',
    'description' => 'Relax, and let your baby find the perfect latch with confidence.',
    'category' => 'position',
    'duration' => '0:48',
    'thumb' => 'public/images/thumbnails/proper_position/proper_position3.jpg',
    'src' => 'public/videos/proper_position/proper_position3.mp4',
  ],
  [
    'id' => 17,
    'title' => 'Football Position',
    'author' => 'Breastfeeding Success',
    'description' => 'Position your little one under your arm, keeping them close and their head steady. Keep their neck and spine in line to ensure a safe, comfortable feeding posture with a football position.',
    'category' => 'position',
    'duration' => '1:30',
    'thumb' => 'public/images/thumbnails/proper_position/proper_position4.jpg',
    'src' => 'public/videos/proper_position/proper_position4.mp4',
  ],
  [
    'id' => 18,
    'title' => 'Side-lying Position',
    'author' => 'SIKANA English',
    'description' => 'In side-lying breastfeeding, the mother can fully rest while the baby feeds, creating a calm and comfortable environment. Keeping the baby’s body aligned with their head supported encourages efficient milk transfer. This position is ideal for reducing strain, promoting bonding, and making feeding sessions peaceful.',
    'category' => 'position',
    'duration' => '2:05',
    'thumb' => 'public/images/thumbnails/proper_position/proper_position5.jpg',
    'src' => 'public/videos/proper_position/proper_position5.mp4',
  ],
//   Techniques
  [
    'id' => 19,
    'title' => 'How to Breast Massage and Hand Express to Remove Milk',
    'author' => 'Sunny Huang - IBCLC',
    'description' => 'Step-by-step demonstration of hand expression techniques and massage tips to help gently express breast milk without a pump.',
    'category' => 'techniques',
    'duration' => '9:21',
    'thumb' => 'public/images/thumbnails/techniques/techniques1.jpg',
    'src' => 'public/videos/techniques/techniques1.mp4',
  ],
  [
    'id' => 20,
    'title' => 'Methods to Increase Low - Milk Supply? ',
    'author' => 'Medical Centric Podcast',
    'description' => 'Expert strategies and tips on enhancing milk supply naturally, including lifestyle changes and nursing tips to support low milk production.',
    'category' => 'techniques',
    'duration' => '3:21',
    'thumb' => 'public/images/thumbnails/techniques/techniques2.jpg',
    'src' => 'public/videos/techniques/techniques2.mp4',
  ],
];
