<?php

$VIDEO_CATEGORIES = [
  ['slug' => 'all',       'name' => 'All'],
  ['slug' => 'latch',     'name' => 'Latch'],
  ['slug' => 'position',  'name' => 'Proper Position'],
  ['slug' => 'problems',  'name' => 'Problems'],
  ['slug' => 'nutrition', 'name' => 'Nutrition'],
  ['slug' => 'anatomy',   'name' => 'Anatomy'],
  ['slug' => 'techniques','name' => 'Techniques'],
];


$VIDEOS = [
    // Latch
  [
    'id' => 1,
    'title' => 'How to latch',
    'author' => 'wikiHow',
    'description' => 'A guide for proper latching and effective breastfeeding technique and making sure the infants are getting fed properly.',
    'category' => 'latch',
    'duration' => '4:01',
    'thumb' => '/MilkyWay/public/images/thumbnails/latch/latch1.jpg',
    'src' => '/MilkyWay/public/videos/latch/latch1.mp4',
  ],
  [
    'id' => 2,
    'title' => 'Latch on ',
    'author' => 'PigeonCorporation',
    'description' => 'A proper latch allows your baby to draw milk efficiently. It promotes steady milk flow, supports healthy weight gain, and encourages a strong milk supply making feeding smoother, more comfortable, and more rewarding for both mother and baby.',
    'category' => 'latch',
    'duration' => '2:28',
    'thumb' => '/MilkyWay/public/images/thumbnails/latch/latch2.jpg',
    'src' => '/MilkyWay/public/videos/latch/latch2.mp4',
  ],
//   Nutrition
  [
    'id' => 3,
    'title' => '15 FOODS PARA DUMAMI ANG BREASTMILK NG BREASTFEEDING MOMMIES!.mp4',
    'author' => 'Healing Galing',
    'description' => 'A practical guide on nutrient tips and diet strategies to support breastfeeding moms’ health, including foods to include for energy, hydration, and milk production',
    'category' => 'nutrition',
    'duration' => '14:12',
    'thumb' => '/MilkyWay/public/images/thumbnails/nutrition/nutrition1.jpg',
    'src' => '/MilkyWay/public/videos/nutrition/nutrition1.mp4',
  ],
  [
    'id' => 4,
    'title' => '10 Foods to Avoid During Breastfeeding | Food Breastfeeding Mother Should Avoid',
    'author' => 'FirstCry Parenting',
    'description' => 'Key guidance on what foods may affect your baby or breast milk negatively so you can adjust your diet with confidence while nursing.',
    'category' => 'nutrition',
    'duration' => '4:06',
    'thumb' => '/MilkyWay/public/images/thumbnails/nutrition/nutrition2.jpg',
    'src' => '/MilkyWay/public/videos/nutrition/nutrition2.mp4',
  ],
  [
    'id' => 5,
    'title' => '10 Best Foods to Increase Breast Milk | How to Increase Breast Milk Supply Quickly',
    'author' => 'FirstCry Parenting',
    'description' => 'Discover the top 10 nutritious foods that can help breastfeeding moms boost milk production and stay energized with healthy, family-friendly nutrition tips.',
    'category' => 'nutrition',
    'duration' => '1:56',
    'thumb' => '/MilkyWay/public/images/thumbnails/nutrition/nutrition3.jpg',
    'src' => '/MilkyWay/public/videos/nutrition/nutrition3.mp4',
  ],
  [
    'id' => 6,
    'title' => '6 Best Fruits to Eat During Breastfeeding | Breastfeeding Diet | Foods To Eat While Breastfeeding',
    'author' => 'FirstCry Parenting',
    'description' => 'Learn which 6 fruits are most beneficial to include in your breastfeeding diet for extra vitamins, hydration, and overall nourishment.',
    'category' => 'nutrition',
    'duration' => '3:51',
    'thumb' => '/MilkyWay/public/images/thumbnails/nutrition/nutrition4.jpg',
    'src' => '/MilkyWay/public/videos/nutrition/nutrition4.mp4',
  ],
//   Anatomy
  [
    'id' => 7,
    'title' => 'Female Breast Structure',
    'author' => 'Kenhub - Learn Human Anatomy',
    'description' => 'Discover the fascinating design and function of the female breast and how it produces and delivers life-nourishing milk.',
    'category' => 'anatomy',
    'duration' => '3:34',
    'thumb' => '/MilkyWay/public/images/thumbnails/anatomy/anatomy1.jpg',
    'src' => '/MilkyWay/public/videos/anatomy/anatomy1.mp4',
  ],
  [
    'id' => 8,
    'title' => 'How Breastfeeding happens?',
    'author' => 'Now Trending',
    'description' => 'From hormonally guided production to its nutrient-packed flow, breast milk is naturally crafted to feed, defend, and build your baby’s strength from the very first drop.',
    'category' => 'anatomy',
    'duration' => '3:41',
    'thumb' => '/MilkyWay/public/images/thumbnails/anatomy/anatomy2.jpg',
    'src' => '/MilkyWay/public/videos/anatomy/anatomy2.mp4',
  ],
//   Problems
  [
    'id' => 9,
    'title' => 'Poor Latch',
    'author' => 'Scottish Government',
    'description' => 'No description',
    'category' => 'problems',
    'duration' => '1:04',
    'thumb' => '/MilkyWay/public/images/thumbnails/problems/problems1.jpg',
    'src' => '/MilkyWay/public/videos/problems/problems1.mp4',
  ],
  [
    'id' => 10,
    'title' => 'Mastitis - Breast pain during lactation or pregnancy. Mastitis symptoms and treatment.',
    'author' => 'Dr. Constantin',
    'description' => 'wikiHow',
    'category' => 'problems',
    'duration' => '2:48',
    'thumb' => '/MilkyWay/public/images/thumbnails/problems/problems2.jpg',
    'src' => '/MilkyWay/public/videos/problems/problems2.mp4',
  ],
  [
    'id' => 11,
    'title' => 'Low Breast Milk Supply – Causes, Signs & Solutions',
    'author' => 'FirstCry Parenting',
    'description' => 'Learning what causes a low milk supply, understanding its signs and applying the solutions to improve breastmilk production.',
    'category' => 'problems',
    'duration' => '4:08',
    'thumb' => '/MilkyWay/public/images/thumbnails/problems/problems3.jpg',
    'src' => '/MilkyWay/public/videos/problems/problems3.mp4',
  ],
  [
    'id' => 12,
    'title' => 'Breast Engorgement ',
    'author' => 'EvergreenHealth',
    'description' => 'Relieve engorgement, restore comfort. Keep your milk supply steady and feed your baby happy and healthy. ',
    'category' => 'problems',
    'duration' => '4:26',
    'thumb' => '/MilkyWay/public/images/thumbnails/problems/problems4.jpg',
    'src' => '/MilkyWay/public/videos/problems/problems4.mp4',
  ],
  [
    'id' => 13,
    'title' => 'Sore or Cracked Nipples ',
    'author' => 'Discover Parenting',
    'description' => 'Exploring the sore or cracked nipples, identifying their causes, and learning effective ways to prevent and treat them.',
    'category' => 'problems',
    'duration' => '2:44',
    'thumb' => '/MilkyWay/public/images/thumbnails/problems/problems5.jpg',
    'src' => '/MilkyWay/public/videos/problems/problems5.mp4',
  ],
//   Proper Position
  [
    'id' => 14,
    'title' => 'How-To: The Cross-Cradle Breastfeeding Position',
    'author' => 'Emma’s Diary',
    'description' => 'a guide on how to do the cross-cradle breastfeeding position.',
    'category' => 'position',
    'duration' => '0:45',
    'thumb' => '/MilkyWay/public/images/thumbnails/proper_position/proper_position1.jpg',
    'src' => '/MilkyWay/public/videos/proper_position/proper_position1.mp4',
  ],
  [
    'id' => 15,
    'title' => 'How-to: The Cradle Breastfeeding Position',
    'author' => 'Emma’s Diary',
    'description' => 'a guide on how to do the cradle breastfeeding position.',
    'category' => 'position',
    'duration' => '0:44',
    'thumb' => '/MilkyWay/public/images/thumbnails/proper_position/proper_position2.jpg',
    'src' => '/MilkyWay/public/videos/proper_position/proper_position2.mp4',
  ],
  [
    'id' => 16,
    'title' => 'How-to: Back-lying Breastfeeding Position',
    'author' => 'Emma’s Diary',
    'description' => 'wikiHow',
    'category' => 'position',
    'duration' => '0:48',
    'thumb' => '/MilkyWay/public/images/thumbnails/proper_position/proper_position3.jpg',
    'src' => '/MilkyWay/public/videos/proper_position/proper_position3.mp4',
  ],
  [
    'id' => 17,
    'title' => 'Breastfeeding-Football Position',
    'author' => 'Breastfeeding Success',
    'description' => 'wikiHow',
    'category' => 'position',
    'duration' => '1:30',
    'thumb' => '/MilkyWay/public/images/thumbnails/proper_position/proper_position4.jpg',
    'src' => '/MilkyWay/public/videos/proper_position/proper_position4.mp4',
  ],
  [
    'id' => 18,
    'title' => 'Breastfeeding in the side-lying position | Breastfeeding',
    'author' => 'SIKANA English',
    'description' => 'wikiHow',
    'category' => 'position',
    'duration' => '2:05',
    'thumb' => '/MilkyWay/public/images/thumbnails/proper_position/proper_position5.jpg',
    'src' => '/MilkyWay/public/videos/proper_position/proper_position5.mp4',
  ],
//   Techniques
  [
    'id' => 19,
    'title' => 'How to Massage and Hand Express to Remove Your Milk | Informative',
    'author' => 'Sunny Huang - IBCLC',
    'description' => 'Step-by-step demonstration of hand expression techniques and massage tips to help gently express breast milk without a pump.',
    'category' => 'techniques',
    'duration' => '9:21',
    'thumb' => '/MilkyWay/public/images/thumbnails/techniques/techniques1.jpg',
    'src' => '/MilkyWay/public/videos/techniques/techniques1.mp4',
  ],
  [
    'id' => 20,
    'title' => 'Mother Milk Magic: Enhancing Low Breast Milk Production',
    'author' => 'Medical Centric Podcast',
    'description' => 'Expert strategies and tips on enhancing milk supply naturally, including lifestyle changes and nursing tips to support low milk production.',
    'category' => 'techniques',
    'duration' => '3:21',
    'thumb' => '/MilkyWay/public/images/thumbnails/techniques/techniques2.jpg',
    'src' => '/MilkyWay/public/videos/techniques/techniques2.mp4',
  ],
];
