CREATE DATABASE MilkyWay;

USE milkyway;
CREATE TABLE feedback (
  feedback_id INT AUTO_INCREMENT PRIMARY KEY,
  rating TINYINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  liked_design BOOLEAN DEFAULT 0,
  liked_content BOOLEAN DEFAULT 0,
  liked_easy BOOLEAN DEFAULT 0,
  liked_tips BOOLEAN DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE daily_tips (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tip_text TEXT NOT NULL,
  is_active TINYINT(1) DEFAULT 1
);
