CREATE DATABASE MilkyWay;
USE MilkyWay;

CREATE TABLE feedback (
  feedback_id INT AUTO_INCREMENT PRIMARY KEY,
  rating TINYINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  liked_design BOOLEAN DEFAULT 0,
  liked_content BOOLEAN DEFAULT 0,
  liked_easy BOOLEAN DEFAULT 0,
  liked_tips BOOLEAN DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
